CREATE TABLE CLIENTE(
  ID INTEGER PRIMARY KEY AUTO_INCREMENTE,
  NOME VARCHAR(100)
);

CREATE TABLE PRODUTO(
  ID INTEGER PRIMARY KEY AUTO_INCREMENTE,
  DESCRICAO VARCHAR(100),
  PRECO DECIMAL(10,2)
);

CREATE TABLE PEDIDO(
  ID INTEGER PRIMARY KEY AUTO_INCREMENTE,
  CLIENTE_ID INTEGER,
  DATA_PEDIDO TIMESTAMP,
  TOTAL NUMERIC(20,2),
  FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE(ID)
);

CREATE TABLE ITEM_PEDIDO(
  ID INTEGER PRIMARY KEY AUTO_INCREMENTE,
  PEDIDO_ID INTEGER,
  PRODUTO_ID INTEGER,
  QUANTIDADE INTEGER,
  PRECO_UNITARIO DECIMAL(10,2),
  FOREIGN KEY (PEDIDO_ID) REFERENCES PEDIDO(ID),
  FOREIGN KEY (PRODUTO_ID) REFERENCES PRODUTO(ID)
);